ShoeMania/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using ShoeMania.Core.Contracts;
using ShoeMania.Core.Services;
using ShoeMania.Core.ViewModels.Order;
using ShoeMania.Data.Models.Enums;
using ShoeMania.Extensions;
using static ShoeMania.Common.NotificationConstants;


namespace ShoeMania.Controllers
{
    public class OrderController : BaseController
    {
		private string url = "https://api.speedy.bg/v1/location/office";
	

        private readonly IUserService userService;
        private readonly IShoeService shoeService;
        private readonly ICustomerService customerService;
        private readonly IOrderService orderService;
        private readonly IPaymentService paymentService;
        private readonly IDeliveryOfficeService deliveryOfficeService;

        public OrderController(IUserService userService, IShoeService shoeService, ICustomerService customerService, IOrderService orderService, IPaymentService paymentService, IDeliveryOfficeService deliveryOfficeService)
        {
            this.userService = userService;
            this.shoeService = shoeService;
            this.customerService = customerService;
            this.orderService = orderService;
            this.paymentService = paymentService;
            this.deliveryOfficeService = deliveryOfficeService;
        }

        [HttpGet]
        public async Task<IActionResult> Order(string paymentId)
        {
            var userId = User.GetId();
            bool isCustomer = await userService.IsCustomerAsync(userId!);

            if (!User.Identity!.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (!isCustomer && !User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            string? userName = User.GetUsername();
            var cartShoes = shoeService.GetCartShoes(userName!);

            OrderFormModel model = new OrderFormModel()
            {
                PaymentId = paymentId,
                Shoes = cartShoes!
            };

            model.Offices = await deliveryOfficeService.GetDeliveryOfficeListAsync(); ;

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Order(OrderFormModel model)
        {
            string userName = User.GetUsername()!;

            if (!ModelState.IsValid)
            {
                model.Shoes = shoeService.GetCartShoes(userName!)!;
                return View(model);
            }

            try
            {

                model.Shoes = shoeService.GetCartShoes(userName!)!;

               

                string? customerId = await customerService.GetCustomerIdByUserIdAsync(User.GetId()!);

                string orderId = await orderService.CreateOrderAsync(model, customerId!);

                await paymentService.AddOrderToPaymentAsync(model.PaymentId, orderId);

            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }

            HttpContext.Session.Clear();
            TempData[SuccessMessage] = "Successful order";
            return RedirectToAction("UserOrders");

        }

		public async Task<IActionResult> UserOrders()
		{
			if (!User.IsInRole("Customer"))
			{
				return RedirectToAction("Index", "Home");
			}

			string? customerId = await customerService.GetCustomerIdByUserIdAsync(User.GetId()!);

			try
			{
				var orders = await orderService.GetCustomerOrdersAsync(customerId!);
				return View("All", orders);

			}
			catch (Exception)
			{
				return RedirectToAction("Index", "Home");
			}

		}
		

		


	}
}

ShoeMania/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using ShoeMania.Core.Contracts;
using ShoeMania.Core.ViewModels.Profile;
using ShoeMania.Extensions;
using static ShoeMania.Common.NotificationConstants;

namespace ShoeMania.Controllers
{
    public class ProfileController : BaseController
    {

        private readonly IProfileService profileService;
        private readonly IUserService userService;

        public ProfileController(IProfileService profileService, IUserService userService)
        {
            this.profileService = profileService;
            this.userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> MyProfile(string userId)
        {
            bool isExists = await userService.IsExistsByIdAsync(userId);
            if (!isExists)
            {
                return RedirectToAction("Index", "Home");
            }

            var profile = await profileService.GetProfileAsync(userId);
            if (profile == null)
            {
                return RedirectToAction("Index", "Home");
            }

            bool isCustomer = await userService.IsCustomerAsync(userId);
            if (!isCustomer)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(profile);

        }

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            bool isExists = await userService.IsExistsByIdAsync(userId);
            if (!isExists)
            {
                return RedirectToAction("Index", "Home");
            }

            if (userId != User.GetId())
            {
                return RedirectToAction("Index", "Home");
            }

            var model = await profileService.GetProfileForEditAsync(userId);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string userId, EditProfileViewModel model)
        {
            bool isExists = await userService.IsExistsByIdAsync(userId);
            if (!isExists)
            {
                return RedirectToAction("Index", "Home");
            }
            if (userId != User.GetId())
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await profileService.EditProfileAsync(userId, model);

            TempData[SuccessMessage] = "Successfully edited profile";

            return RedirectToAction("MyProfile", new { userId });
        }

        
    }
}

ShoeMania/Controllers/ShoesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShoeMania.Core.Contracts;
using ShoeMania.Core.Extensions;
using ShoeMania.Core.ViewModels.Shoes;
using ShoeMania.Extensions;
using static ShoeMania.Common.NotificationConstants;

namespace ShoeMania.Controllers
{
    public class ShoesController : BaseController
    {
        private readonly IShoeService shoeService;
        private readonly IUserService userService;
        private readonly ICategoryService categoryService;
        private readonly ISizeService sizeService;

        public ShoesController(IShoeService shoeService, IUserService userService, ICategoryService categoryService, ISizeService sizeService)
        {
            this.shoeService = shoeService;
            this.userService = userService;
            this.categoryService = categoryService;
            this.sizeService = sizeService;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All(ShoesQueryModel model)
        {
            var userId = User.GetId();
            bool isCustomer = await userService.IsCustomerAsync(userId!);

            if (!isCustomer && !User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            try
            {
                AllShoesFilteredAndPaged serviceModel = await shoeService.GetAllShoesFilteredAndPagedAsync(model);
                model.TotalShoes = serviceModel.TotalShoes;
                model.Shoes = serviceModel.Shoes.ToList();
                model.Categories = await categoryService.GetAllCategoryNamesAsync();

                return View(model);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }


        }

        [AllowAnonymous]
        public async Task<IActionResult> RemoveFromCart(string shoeId)
        {
            bool isExists = await shoeService.IsExistsAsync(shoeId);

            if (!isExists)
            {
                return RedirectToAction("All");
            }

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            var shoes = HttpContext.Session.GetObjectFromJson<List<OrderShoeViewModel>>($"cart{User.GetUsername()}");

            if (shoes!.Count > 0)
            {
                var shoeToRemove = shoes.FirstOrDefault(d => d.Id == shoeId);
                if (shoes.Remove(shoeToRemove!))
                {
                    HttpContext.Session.SetObjectAsJson($"cart{User.GetUsername()}", shoes);
                }
                else
                {
                    HttpContext.Session.SetObjectAsJson($"cart{User.GetUsername()}", shoes);

                    TempData[SuccessMessage] = "Successfully removed from cart";

                    return RedirectToAction("Cart");
                }
            }

            TempData[SuccessMessage] = "Successfully removed from cart";


            return RedirectToAction("Cart");
        }

        //[HttpGet]
        //public async Task<IActionResult> Add()
        //{
        //    if (!User.IsInRole("Admin"))
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }

        //    ShoeFormModel model = new ShoeFormModel();
        //    model.Categories = await categoryService.GetAllCategoriesAsync();
        //    model.Sizes = await sizeService.GetAllSizesAsync();

        //    return View(model);
        //}

        //[HttpPost]
        //public async Task<IActionResult> Add(ShoeFormModel model)
        //{
        //    if (!User.IsInRole("Admin"))
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }

        //    if (!ModelState.IsValid)
        //    {
        //        model.Categories = await categoryService.GetAllCategoriesAsync();
        //        model.Sizes = await sizeService.GetAllSizesAsync();

        //        return View(model);
        //    }

        //    string shoeId = await shoeService.AddAsync(model);

        //    await sizeService.AddSizesToShoeAsync(model.SizeIds, shoeId);

        //    TempData[SuccessMessage] = "Successfuly added shoe";

        //    return RedirectToAction("All");


        //}

        //[HttpGet]
        //public async Task<IActionResult> Edit(string shoeId)
        //{
        //    if (!User.IsInRole("Admin"))
        //    {
        //        TempData[ErrorMessage] = "Your should be admin to edit shoe";
        //        return RedirectToAction("All");
        //    }

        //    bool isExists = await shoeService.IsExistsAsync(shoeId);

        //    if (!isExists)
        //    {
        //        TempData[ErrorMessage] = "This shoe does not exist";
        //        return RedirectToAction("All");
        //    }

        //    try
        //    {
        //        var shoe = await shoeService.GetShoeForEditAsync(shoeId);

        //        return View(shoe);
        //    }
        //    catch (Exception)
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }

        //}

        //[HttpPost]
        //public async Task<IActionResult> Edit(string shoeId, ShoeFormModel model)
        //{
        //    if (!User.IsInRole("Admin"))
        //    {
        //        TempData[ErrorMessage] = "Your should be admin to edit shoe";
        //        return RedirectToAction("All");
        //    }

        //    bool isExists = await shoeService.IsExistsAsync(shoeId);

        //    if (!isExists)
        //    {
        //        TempData[ErrorMessage] = "This shoe does not exist";
        //        return RedirectToAction("All");
        //    }

        //    if (!ModelState.IsValid)
        //    {
        //        return View(model);
        //    }



        //    await shoeService.EditShoeAsync(model, shoeId);

        //    TempData[SuccessMessage] = "Successfully edited shoe";

        //    return RedirectToAction("All");

        //}

        //[HttpGet]
        //public async Task<IActionResult> Delete(string shoeId)
        //{
        //    if (!User.IsInRole("Admin"))
        //    {
        //        TempData[ErrorMessage] = "Your should be admin to edit shoe";
        //        return RedirectToAction("All");
        //    }

        //    bool isExists = await shoeService.IsExistsAsync(shoeId);

        //    if (!isExists)
        //    {
        //        TempData[ErrorMessage] = "This shoe does not exist";
        //        return RedirectToAction("All");
        //    }

        //    var shoe = await shoeService.GetShoeForDeleteAsync(shoeId);

        //    TempData[WarningMessage] = "If you press the button delete you will delete this shoe";
        //    return View(shoe);

        //}

        //[HttpPost]
        //public async Task<IActionResult> Delete(string shoeId, PreDeleteShoeViewModel model)
        //{
        //    if (!User.IsInRole("Admin"))
        //    {
        //        TempData[ErrorMessage] = "Your should be admin to edit shoe";
        //        return RedirectToAction("All");
        //    }

        //    bool isExists = await shoeService.IsExistsAsync(shoeId);

        //    if (!isExists)
        //    {
        //        TempData[ErrorMessage] = "This shoe does not exist";
        //        return RedirectToAction("All");
        //    }

        //    await shoeService.DeleteShoeAsync(shoeId);

        //    TempData[SuccessMessage] = "Successfully delete shoe";

        //    return RedirectToAction("All");
        //}

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            bool isExists = await shoeService.IsExistsAsync(id);
            if (!isExists)
            {
                return RedirectToAction("All");
            }

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            var model = await shoeService.GetDetailsForShoeAsync(id);

            return View(model);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Cart()
        {
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (!User.Identity!.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }

            string? userName = User.GetUsername();
            var cartShoes = shoeService.GetCartShoes(userName!);

            return await Task.Run(() => View(cartShoes));

        }

        public async Task<IActionResult> AddToCart(DetailsShoeViewModel model)
        {
            string shoeId = model.Id;
            bool isExists = await shoeService.IsExistsAsync(shoeId);

            if (!isExists)
            {
                return RedirectToAction("All");
            }

            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("Index", "Home");
            }

            string userName = User.GetUsername()!;
            await shoeService.AddShoeToCart(userName, shoeId, model.Size);

            TempData[SuccessMessage] = "Successfully added to cart";

            return RedirectToAction("Cart");


        }
    }
}

ShoeMania/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using ShoeMania.Extensions
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/responsive.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header class="header_section">
        <div class="header_top"
             style="background-color:black">

            <div class="container-fluid">
                <div class="top_nav_container">
                    <div class="user_option_box">
                        @if (User.Identity!.IsAuthenticated)
                        {
                            <a asp-action="MyProfile" asp-controller="Profile" asp-route-userId="@User.GetId()" class="account-link">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                <span>
                                    My Account
                                </span>
                            </a>
                        }

                        <a asp-action="Cart" asp-controller="Shoes" class="cart-link">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            <span>
                                Cart
                            </span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
        <div class="header_bottom"
             style="background-color:black">
            <div class="container-fluid">
                <partial name="_NotificationPartial" />

                <nav class="navbar navbar-expand-lg custom_nav-container  ">
                    <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                        <span>
                            Shoe Mania
                        </span>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class=""> </span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ">
                            <li class="nav-item active">
                                <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
                            </li>

                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="Admin" asp-controller="Shoe" asp-action="All">Products</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link" asp-action="WhyUs" asp-controller="Home">Why Us</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-action="Add" asp-controller="Shoe">Add Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-action="AdminOrders" asp-controller="Order">My Orders</a>
                            </li>




                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </nav>
            </div>
        </div>
    </header>


    @RenderBody()

    <section class="info_section"
             style="background-color:black">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="info_contact">
                        <h5>
                            <a asp-action="Index" asp-controller="Home" class="navbar-brand">
                                <span>
                                    Shoe Mania
                                </span>
                            </a>
                        </h5>
                        <p>
                            <i class="fa fa-map-marker" aria-hidden="true"></i>
                            Address
                        </p>

                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info_info">
                        <h5>
                            Welcome to Shoe Mania – Your Ultimate Footwear Destination!
                        </h5>
                        <p>
                            At Shoe Mania, we believe every step you take deserves to be comfortable, stylish, and unforgettable. Our online store offers an extensive collection of footwear for men, women, and kids, catering to every style, occasion, and need. Whether you’re looking for trendy sneakers, elegant heels, durable boots, or comfortable sandals, we’ve got you covered!
                        </p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info_links">
                        <h5>
                            Useful Link
                        </h5>
                        <ul>
                            <li>
                                <a asp-action="Index" asp-controller="Home">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a asp-action="WhyUs" asp-controller="Home">
                                    Why Us
                                </a>
                            </li>
                            <li>
                                <a asp-action="All" asp-controller="Shoes">
                                    Products
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="info_form ">
                        <h5>
                            Newsletter
                        </h5>
                        <form action="">
                            <input type="email" placeholder="Enter your email">
                            <button>
                                Subscribe
                            </button>
                        </form>
                        @* <div class="social_box">
                        <a href="">
                        <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <a href="">
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <a href="">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                        </a>
                        <a href="">
                        <i class="fa fa-youtube" aria-hidden="true"></i>
                        </a>
                        </div> *@
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer class="footer_section"
            style="background-color:black">
        <div class="container">
            <p>
                &copy; <span id="displayYear"></span> All Rights Reserved By
                <a href=""> ShoeMania</a>
            </p>
        </div>
    </footer>

    <script src="https://kit.fontawesome.com/b9403dda92.js" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ShoeMania/Areas/Admin/Views/Shared/_ShoePartial.cshtml
@using ShoeMania.Extensions
@model ShoeMania.Core.ViewModels.Shoes.ShoeViewModel


<div class="product" style="margin-left: 3rem; margin-top: 5rem;margin-bottom: 100px">
    <span class="product__price">@Model.Price lv.</span>
    <img class="product__image" height="300" src="@Model.ShoePictureUrl" style="height:auto">
    <h1 class="product__title">@Model.Name</h1>
    <hr />
    <p>
        @Model.Description
    </p>
    @if (User.IsInRole("Customer"))
    {
        <a asp-action="Details" asp-controller="Shoes" asp-route-id="@Model.Id" class="product__btn btn-buy">Buy Now</a>

    }
    else
    {
        <div class="d-flex" style="justify-content: space-between">
            <a asp-area="Admin" asp-action="Edit" asp-controller="Shoe" asp-route-shoeId="@Model.Id" class="product__btn-edit btn-buy" style="margin-right: 50%">Edit</a>
            <a asp-area="Admin" asp-action="Delete" asp-controller="Shoe" asp-route-shoeId="@Model.Id" class="product__btn btn-buy">Delete</a>
        </div>

    }
</div>